
# AGE09: ¿Qué eventos forman parte de otros eventos?

PREFIX edintagenda: <http://vocab.linkeddata.es/datosabiertos/def/cultura-ocio/agenda#>
PREFIX schema: <https://schema.org/>
PREFIX edintinf: <http://vocab.linkeddata.es/datosabiertos/def/urbanismos-infraestructuras/infraestructura#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX gsp: <http://www.opengis.net/ont/geosparql#>

SELECT ?event ?subevent
WHERE {
  ?event a schema:Event ;
         schema:subEvent ?subevent .
}